### ISSUE TITLE
ini gimana ya?

### ISSUE THREAD

**Issue by natxdixie** [Awesomesh0t/awesomeshot#30]
![Screenshot_2022-10-20-02-19-42-50_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83612604/196784175-d5a46fee-714c-4425-8d1f-a279bae97438.jpg)

**Comment by armandwipangestu** [comment]
v1.1.0 has a little bug, you can try the latest version it might solve your problem

https://github.com/Awesomesh0t/awesomeshot/issues/25#issuecomment-1243678634

**Comment by armandwipangestu** [comment]
Udah install dependency package nya?

**Comment by natxdixie** [comment]
> Udah install dependency package nya?

udah

**Comment by armandwipangestu** [comment]
Configurasi nya udah bener di bagian `screenshot_path` nya?

![image](https://user-images.githubusercontent.com/64394320/196789151-0d497e26-7c33-40fe-aa6e-f5bc028a2768.png)

pastikan di isi dengan folder hasil screenshot device nya

**Comment by natxdixie** [comment]
> Configurasi nya udah bener di bagian `screenshot_path` nya?
> 
> ![image](https://user-images.githubusercontent.com/64394320/196789151-0d497e26-7c33-40fe-aa6e-f5bc028a2768.png)
> 
> pastikan di isi dengan folder hasil screenshot device nya karena tiap device beda - beda dan kalo folder nya gk ada dia gk akan jalan
> 
> https://github.com/Awesomesh0t/awesomeshot/wiki/Customizing-Config-File#screenshot-result-path
> 
> dan coba upgrade ke versi terbaru `v1.2.0` [#25 (comment)](https://github.com/Awesomesh0t/awesomeshot/issues/25#issuecomment-1243678634)

![Screenshot_2022-10-20-03-16-09-49_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83612604/196795013-72f9d3ff-cec6-4def-ab86-baccbc2fb6ba.jpg)
udah make install padahal td

**Comment by armandwipangestu** [comment]
Coba install package `ncurses-utils`

```bash
pkg i -y ncurses-utils
```

lalu jalankan kembali dan ambil screenshot

**Comment by natxdixie** [comment]
> Coba install package `ncurses-utils`
> 
> ```shell
> pkg i -y ncurses-utils
> ```
> 
> lalu jalankan kembali dan ambil screenshot

nah bisa, tp pas ss ga kedetect

**Comment by armandwipangestu** [comment]
> nah bisa, tp pas ss ga kedetect

Coba liat config pas bagian `screenshot_path` nya

**Comment by armandwipangestu** [comment]
Halo, apakah sudah solved?

**Comment by yosafatreza** [comment]
.........................convert: unable to read font `Arial' @ warning/annotate.c/RenderType/1024.
convert: unable to read font `Arial' @ error/annotate.c/RenderFreetype/1654.
convert: unable to read font `Arial' @ warning/annotate.c/RenderType/1024.
convert: unable to read font `Arial' @ error/annotate.c/RenderFreetype/1654.
