### ISSUE TITLE
awesomeshot is stucking

### ISSUE THREAD

**Issue by OurCodeBase** [Awesomesh0t/awesomeshot#35]
I'm using awesomeshot in termux, it works finely until this line.
```conf
[+] Set Image Second Border Gradient .list
```
How to fix it ?

**Comment by OurCodeBase** [comment]
I updated awesomeshot from 1.1.0 to 1.2.0 but now it works very weirdly.

![IMG_20231008_102139](https://github.com/Awesomesh0t/awesomeshot/assets/100824266/376851c7-4235-455a-af8d-f7c27b148859)

**Comment by armandwipangestu** [comment]
awesomeshot have 2 option

1. Automatic mode
2. Manual mode

You can read more about the explanation of how awesomeshot works here https://github.com/Awesomesh0t/awesomeshot/issues/2#issuecomment-1052047095
